// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfwTg6BVsXQDwHy5epHCgNJ0y7aTtZikA',
    appId: '1:907528221988:web:43acb0e6ed28ce4377efb1',
    messagingSenderId: '907528221988',
    projectId: 'prueba-base-de-datos-8c79f',
    authDomain: 'prueba-base-de-datos-8c79f.firebaseapp.com',
    storageBucket: 'prueba-base-de-datos-8c79f.firebasestorage.app',
    measurementId: 'G-1VPRD7CZYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYaxwfIEdef4hKPFI5eweoNQvKsQ19Hpw',
    appId: '1:907528221988:android:cee785fc6075354c77efb1',
    messagingSenderId: '907528221988',
    projectId: 'prueba-base-de-datos-8c79f',
    storageBucket: 'prueba-base-de-datos-8c79f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmysgb8_d4X_v8u9-JP3CpNgaEHwRccN4',
    appId: '1:907528221988:ios:48b93d6ec585c17177efb1',
    messagingSenderId: '907528221988',
    projectId: 'prueba-base-de-datos-8c79f',
    storageBucket: 'prueba-base-de-datos-8c79f.firebasestorage.app',
    iosBundleId: 'com.example.theHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmysgb8_d4X_v8u9-JP3CpNgaEHwRccN4',
    appId: '1:907528221988:ios:48b93d6ec585c17177efb1',
    messagingSenderId: '907528221988',
    projectId: 'prueba-base-de-datos-8c79f',
    storageBucket: 'prueba-base-de-datos-8c79f.firebasestorage.app',
    iosBundleId: 'com.example.theHero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfwTg6BVsXQDwHy5epHCgNJ0y7aTtZikA',
    appId: '1:907528221988:web:4e2867c0fa0ee52277efb1',
    messagingSenderId: '907528221988',
    projectId: 'prueba-base-de-datos-8c79f',
    authDomain: 'prueba-base-de-datos-8c79f.firebaseapp.com',
    storageBucket: 'prueba-base-de-datos-8c79f.firebasestorage.app',
    measurementId: 'G-M7J6P8014D',
  );

}