// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTZaV9wUqdZmL6Pn6iLsk_mMMvHMk4GE4',
    appId: '1:9377083728:web:1ceb5d910fc7122815fc55',
    messagingSenderId: '9377083728',
    projectId: 'the-hero-67d93',
    authDomain: 'the-hero-67d93.firebaseapp.com',
    storageBucket: 'the-hero-67d93.firebasestorage.app',
    measurementId: 'G-M9WJWKCDMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwofE_RVjEKc6LxbGFcZtVHEs8u0jJJog',
    appId: '1:9377083728:android:38d812eb52ef486715fc55',
    messagingSenderId: '9377083728',
    projectId: 'the-hero-67d93',
    storageBucket: 'the-hero-67d93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ghHN05o2YOOaKtqDRDhfmUFRwiWLZ-M',
    appId: '1:9377083728:ios:23bd0652c94bf5e015fc55',
    messagingSenderId: '9377083728',
    projectId: 'the-hero-67d93',
    storageBucket: 'the-hero-67d93.firebasestorage.app',
    iosBundleId: 'com.example.theHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ghHN05o2YOOaKtqDRDhfmUFRwiWLZ-M',
    appId: '1:9377083728:ios:23bd0652c94bf5e015fc55',
    messagingSenderId: '9377083728',
    projectId: 'the-hero-67d93',
    storageBucket: 'the-hero-67d93.firebasestorage.app',
    iosBundleId: 'com.example.theHero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTZaV9wUqdZmL6Pn6iLsk_mMMvHMk4GE4',
    appId: '1:9377083728:web:d5311a65a4bfe67715fc55',
    messagingSenderId: '9377083728',
    projectId: 'the-hero-67d93',
    authDomain: 'the-hero-67d93.firebaseapp.com',
    storageBucket: 'the-hero-67d93.firebasestorage.app',
    measurementId: 'G-E0G6G2RN21',
  );

}